"""commit

Revision ID: 5fc593586522
Revises: 545afafaf373
Create Date: 2023-03-22 14:50:55.144227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc593586522'
down_revision = '545afafaf373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'lessons', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'lessons', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
