"""commit

Revision ID: 7eeb1105d846
Revises: 
Create Date: 2023-03-24 12:07:29.734698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from src import scripts
from src.auth.models import staf_as_dict

revision = '7eeb1105d846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('staff_role', scripts.choice_field.ChoiceType(staf_as_dict), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=99), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=99), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffs')
    # ### end Alembic commands ###
