"""commit

Revision ID: 9000e16781e2
Revises: 62703964e88d
Create Date: 2023-03-22 17:08:41.942514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9000e16781e2'
down_revision = '62703964e88d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
