"""commit

Revision ID: a73561283c1c
Revises: 2c5927ae92d9
Create Date: 2023-03-22 17:04:13.607118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73561283c1c'
down_revision = '2c5927ae92d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teachers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    # ### end Alembic commands ###
